language: python
services:
  - docker
  
before_script:
  - docker run -d -p 6379:6379 -it --rm --name redisgraph redislabs/redisgraph:2.0-edge

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"
install:
  - pip install -e git+https://github.com/RedisGraph/redisgraph-py#egg=redisgraph
  - pip install -e git+https://github.com/HTTP-APIs/hydra-python-core#egg=hydra_python_core
  - pip install -e .
  
script: python -m unittest discover
